services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: laval
      POSTGRES_PASSWORD: laval
      POSTGRES_DB: laval
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
