apiVersion: apps/v1
kind: Deployment
metadata:
  name: laval-manager
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      app: laval-manager
  template:
    metadata:
      labels:
        app: laval-manager
    spec:
      containers:
        - name: laval-manager
          image: {{ .Values.manager.image }}
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: laval-db-secret
                  key: database-url
            - name: RUST_LOG
              value: {{ .Values.manager.logLevel }}
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50051
              name: grpc