apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: laval-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      hostname: "{{ .Values.domain }}"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same