apiVersion: v1
kind: Secret
metadata:
  name: laval-db-secret
type: Opaque
data:
  postgres-password: {{ .Values.db.password | b64enc }}
  database-url: {{ printf "postgres://%s:%s@laval-db:5432/%s" .Values.db.user .Values.db.password .Values.db.database | b64enc }}