apiVersion: v1
kind: Service
metadata:
  name: laval-db
  labels:
    app: laval-db
spec:
  clusterIP: None
  selector:
    app: laval-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432