apiVersion: v1
kind: Service
metadata:
  name: laval-manager
  labels:
    app: laval-manager
spec:
  selector:
    app: laval-manager
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051