apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: laval-db
spec:
  serviceName: laval-db
  replicas: 1
  selector:
    matchLabels:
      app: laval-db
  template:
    metadata:
      labels:
        app: laval-db
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: pgduckdb/pgduckdb:17-v1.0.0
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.database }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laval-db-secret
                  key: postgres-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: laval-db-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.db.storage }}