name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push laval-manager image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: crates/manager/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/laval-manager:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/laval-manager:latest

      - name: Render Kubernetes manifests
        env:
          LAVAL_MANAGER_IMAGE: ghcr.io/${{ github.repository_owner }}/laval-manager:${{ github.sha }}
        run: |
          envsubst < k8s/laval.yaml > k8s/laval.rendered.yaml
          cat k8s/laval.rendered.yaml

      - name: Apply manifests
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f k8s/laval.rendered.yaml
